// filepath: /home/unknown/Documents/testing_to_be_deleted/university_names.js
module.exports = [
  "Pondicherry University",
  "Dr. YSR University of Health Sciences",
  "Statutory Autonomous, AIIMS(New Delhi)",
  "Gandhi Institute of Technology and Management (GITAM University) Deemed, Visakhapatnam",
  "Sri Venkateswara Institute of Medical Sciences (SVIMS), Tirupati",
  "Rajiv Gandhi University",
  "Statutory Autonomous, AIIMS (Guwahati)",
  "Srimanta Shankardeva University of Health Sciences",
  "Aryabhatta Knowledge University, Patna",
  "Bihar University of Health Sciences",
  "Indira Gandhi Instt of Medical Sciences (Deemed University), Patna",
  "Al-Karim University, Katihar",
  "B.N. Mandal University",
  "Mata Gujri University, Bihar",
  "Gopal Narayan Singh University",
  "Bhupendra Narayan Mandal University, Madhepura",
  "Punjab University",
  "Pt. Deendayal Upadhyay Memorial Health Sciences and Ayush University, Raipur",
  "Statutory Autonomous, AIIMS(Raipur)",
  "Pt.Ravishankar Shukla University (Prev. Ravishankar University),Raipur",
  "Pandit Deendayal Upadhyay Memorial Health Science & Ayush University of Chattisgarh",
  "Veer Narmad South Gujarat University",
  "Guru Gobind Singh Indraprastha University",
  "University of Jamia Hamdard (Hamdard University)",
  "Delhi University",
  "Goa University",
  "Statutory Autonomous, AIIMS (Rajkot)",
  "Gujarat University",
  "Hemchandracharya North Gujarat University,Patan",
  "Saurashtra University",
  "Dharmsinh Desai University, Nadiad",
  "MS University of Baroda",
  "Bhakta Kavi Narsing Mehta University, Bikha Roa, Khadia",
  "Maharaja Krishnakumarsinghji Bhavnagar University",
  "Saurashtra University, Rajkot",
  "Shri Govind Guru University, Godhara",
  "KSKV Kachchh University, Bhuj",
  "Sankalchand Patel University",
  "Parul University, Vadodara",
  "Bhaikaka University",
  "Sumandeep Vidyapeeth University (Deemed), Vadodra",
  "Swaminayaran University",
  "PT. B.D. Sharma University of Health Sciences, Rohtak",
  "Al-Falah University",
  "Amrita Vishwa Vidyapeetham University (Deemed), Coimbatore",
  "SGT University, Gurugram",
  "Maharishi Marakandeshwar University (Deemed), Ambala",
  "Statutory Autonomous, AIIMS (Bilaspur)",
  "Himachal Pradesh University",
  "Maharishi Marakandeshwar University, Kumarhatti, Solan",
  "Jammu University",
  "Statutory Autonomous, AIIMS (Vijaypur)",
  "Kashmir University",
  "University of Kashmir",
  "University of Jammu",
  "Deemed University, Jammu & Kashmir",
  "Statutory Autonomous, AIIMS(Deoghar)",
  "Sidho Kanhu Murmu University",
  "Binod Bihati Mahto Koyalanchal University, Dhanbad",
  "Ramchandra Chandravansi University, Bishrampur, Palamu",
  "Manipal University, Manipal",
  "Kolhan University, Chaibasa",
  "Nilamber-Pitamber University",
  "Ranchi University",
  "Adichunchanagiri University",
  "Rajiv Gandhi University of Health Sciences, Karnataka",
  "Dayananda Sagar University, Bangalore",
  "KLE Academy of Higher Education & Research (Deemed), Belgaum",
  "JSS Academy of Higher Education & Research, Mysuru (formerly known as JSS University, Mysore)",
  "Manipal Academy of Higher Education (Deemed University), Manipal",
  "Khaja Bandanawaz University",
  "Nitte University (Deemed), Mangalore",
  "M.S. Ramaiah University of Applied Sciences, Bangalore.",
  "PES University",
  "Shri Dharmasthala Manjunatheshwara University, Karnataka",
  "Sri Devaraj Urs Academy of Higher Education and Research (Deemed University), Kolar",
  "Sri Sathya Sai University for Human Excellence",
  "Sri Siddhartha Academy of Higher Education, Tumkur",
  "Yenepoya University (Deemed Manglore)",
  "Kerala University of Health Sciences, Thrissur, Kerala",
  "Kerala University, Thiruvananthapuram",
  "Calicut University",
  "Kerala University of Health Sciences",
  "Statutory Autonomous, AIIMS(Bhopal)",
  "Amaltas University, Dewas",
  "Madhya Pradesh Medical Science University, Jabalpur",
  "Chirayu University, Bhopal (M.P)",
  "Jiwaji University",
  "Madhya Pradesh Medical Science University",
  "Malwanchal University, Indore",
  "LNCT University, Bhopal",
  "Rani Durgavati Vishwa Vidyalaya, Jabalpur",
  "Peoples University, Bhopal",
  "Barkatullah University",
  "Vikram University, Ujjain",
  "Sri Aurobindo University",
  "Maharashtra University of Health Sciences, Nashik",
  "Bharati  Vidyapeeth University (Deemed), Pune",
  "Datta Meghe Institute of Higher Education & Research (Declared as Deemed to be University)",
  "Dr. D Y Patil University (Deemed), Pimpri, Pune",
  "D.Y. Patil Education Society (Deemed University), Kolhapur",
  "Krishna Vishwa Vidyapeeth, Karad, Maharashtra",
  "MGM Institute of Health Sciences (Deemed University), Navi Mumbai",
  "MGM Institute of Health Sciences",
  "Padmashree Dr. D Y Patil University (Deemed), Navi Mumbai",
  "Pravara Institute of Medical Sciences (Deemed University), Ahmednagar",
  "Symbiosis International (Deemed) University, pune",
  "Manipur University",
  "North Eastern Hill University, Shillong",
  "University of Science and Technology, Meghalaya",
  "Mizoram University",
  "Nagaland University",
  "MSCBD University, Baripada",
  "Utkal University",
  "The Orissa University Of Health Sciences, Bhubaneswar",
  "Sambalpur University",
  "Fakir Mohan Univeristy, Balasore",
  "Siksha O Anusandhan University,Bhubaneswar",
  "KIIT University (Deemed), Bhubaneswar",
  "Berhampur University",
  "North Odisha University, Baripada, Odisha",
  "The Kalahandi university",
  "Vinayaka Missions University (Deemed), Salem",
  "Statutory Autonomous, Puducherry",
  "Sri Balaji Vidyapeeth (Deemed University), Pondicherry",
  "Bharath Institute of Higher Education & Research (Deemed Univ.), Chennai",
  "Adesh University, Bathinda",
  "Baba Farid University of Health Sciences,Faridkot",
  "RIMT University",
  "Sri Guru Ram Das University of Health Sciences, Sri Amritsar",
  "Marwar Medical University, Jodhpur",
  "Tantia University",
  "Rajasthan University of Health Sciences",
  "Geetanjali University , Udaipur",
  "Rajasthan University of Medical Sciences",
  "Jaipur National University (Private Univ.)",
  "Rajasthan University",
  "Mahatma Gandhi University of Medical Science & Technology, Jaipur",
  "NIMS University (Deemed), Jaipur",
  "Sai Tirupati University, Udaipur",
  "Pacific Medical University, Udaipur",
  "Sikkim Manipal Univ. of Health,Medical & Tech. Scs",
  "Dr. MGR Educational and Research Institute (Deemed University), Chennai",
  "Statutory Autonomous, AIIMS (Madurai)",
  "Dr. M.G.R. University of Health Sciences, Tamilnadu",
  "The Tamilnadu Dr. MGR Medical University,Chennai",
  "Chettinad Academy of Research and Education (Deemed University), Chettinad",
  "Dhanalakshmi Srinivasan University, a state private University of Tamil Nadu",
  "St. Joseph University",
  "Meenakshi University (Deemed), Chennai",
  "Annamalai University",
  "Saveetha University (Deemed), Chennai",
  "Sri Ramachandra Institute of Higher Education & Research(Deemed to be University), Chennai",
  "Sri Venkateswaraa University, Chennai",
  "SRM Institute  of Science & Technology (Formerly SRM University)",
  "Vels Institute Of Science, Technology & Advanced Studies( VISTAS) ( Deemed to be University)",
  "Kaloji Narayana Rao University of Health Sciences, Warangal",
  "Anurag University",
  "Tripura University",
  "Hemwati Nandan Bahuguna Uttarakhand Medical Education University, Dehradun",
  "Ras Bihari Bose Subharti University, Dehradun",
  "H.N.B. Uttarakhand Medical University",
  "Kumaon University, Nainital",
  "Graphic Era Institute of Medical Sciences Dehradun, Uttrakhand",
  "Swami Rama Himalayan University, Dehradun",
  "Shri Guru Ram Rai University",
  "HNB Uttarakhand Medical Education University, Dehradun",
  "Hemwati Nandan Bahuguna Uttarakhand Medical Education University",
  "Atal Bihari Vajpayee Medical University, Lucknow, Uttar Pradesh",
  "Deen Dayal Upadhyay Gorakhpur University, Gorakhpur",
  "Dr. Ram Manohar Lohia Avadh University, Faizabad",
  "King Georges Medical University,Lucknow",
  "Dr B R Ambedkar University,Agra, U.P.",
  "Mahatma Jyotiba Phule Rohilkhand University",
  "Ch. Charan Singh Universitiy, Meerut",
  "C.S.J.M. University, Kanpur",
  "Mahatma Gandhi Kashi Vidyapith, Varanasi",
  "Banaras Hindu University",
  "Integral University, Lucknow",
  "Aligarh Muslim University",
  "Bundelkhand University",
  "Noida International University",
  "M J P Rohilkhand University",
  "Bareilly International University, Bareilly",
  "Santosh University",
  "CSJM University Kanpur",
  "Sharda University, Greater Noida",
  "Mahayogi Gorakhnath University Gorakhpur, Uttar Pradesh",
  "SKS International University",
  "Swami Vivekanand Subharti University, Meerut",
  "Teerthanker Mahaveer University, Moradabad",
  "Atal Bihari Vijpayee Medical University (ABVMU), Lucknow",
  "Prof. Rajendra Singh (Rajju Bhaiya) University, Prayagraj",
  "Uttar Pradesh University of Medical Sciences, Etawah",
  "Shri Venkateshwara University, Gajraula",
  "West Bengal University of Health Sciences,Kolkata",
  "The West Bengal University of Health Sciences",
  "JIS University, Kolkata"
];
